/**
 * Example gameState object for a two-player set/legs darts game.
 * Save the current version of this object (as JSON) in your database for each game.
 */

export default {
  players: [
    { id: 1, name: "Bob Sheruncle" },
    { id: 2, name: "Tony Fogarty" },
  ],
  settings: {
    sets: 5,       // Best of 5 sets
    legsPerSet: 5, // Best of 5 legs per set
    suddenDeath: true, // or false
    startScore: 501,
    throwFirst: 1,  // 1 or 2 (player id)
    format: "sets", // or "legs"
  },
  current: {
    set: 0, // zero-based index
    leg: 0, // zero-based index
    turn: 1, // player id (1 or 2) - always the next player to throw
  },
  sets: [
    // Each set contains a list of legs (order matters!)
    {
      legs: [
        // Each leg contains throws per turn, and winner if finished
        {
          throws: [
            // Each turn: { playerId, scored, remaining, darts, bust, checkout }
            // Example: { playerId: 1, scored: 100, remaining: 401, darts: 3, bust: false }
          ],
          winner: null, // 1 or 2 when finished
          winningTurn: null, // index in throws array of the winning throw, for stats/highlights
        },
        // ...more legs
      ],
      winner: null, // 1 or 2 when set is won
    },
    // ...more sets
  ],
  winner: null, // 1 or 2 when match is won
  stats: null,  // Will be generated by stats logic, can be null until needed
}